image: iryo/ci:latest

variables:
  GO_DIR: "/go/src/github.com/iryonetwork/wwm"

before_script:
  - 'mkdir -p $GO_DIR && cp -r . $GO_DIR'
  - 'cd $GO_DIR && make'

unit:
  script: 'cd $GO_DIR && make test'
