version: "3"
services:
  traefik:
    build:
      context: .
      dockerfile: Dockerfile.traefik
    image: traefik:1.4-alpine
    command:
    - --configfile=/etc/traefik.toml
    - --debug
    volumes:
    - ./traefik.toml:/etc/traefik.toml
    - ./bin/tls:/certs
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 80:80
    - 443:443
    - 8080:8080

  vault:
    image: vault
    environment:
    - VAULT_DEV_ROOT_TOKEN_ID=root
    - VAULT_DEV_LISTEN_ADDRESS=127.0.0.1:8800
    cap_add:
    - IPC_LOCK
    ports:
    - 8200:8200
    volumes:
    - ./.data/vault:/data
    - ./bin/tls:/certs
    - ./vault.hcl:/vault/config/local.hcl

  vaultui:
    image: djenriquez/vault-ui
    environment:
    - VAULT_URL_DEFAULT=https://vault:8200
    - VAULT_AUTH_DEFAULT=TOKEN
    - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
    - vault

  localAuth:
    image: golang:1.9-alpine
    command:
    - /wwm/localAuth
    volumes:
    - ./.bin/:/wwm
    - ./bin/tls:/certs
    environment:
    - DEBUG=1

  localStorage:
    image: golang:1.9-alpine
    command:
    - /wwm/localStorage
    volumes:
    - ./.bin/:/wwm
    - ./bin/tls:/certs:ro
    - ./bin/tls/ca.pem:/etc/ssl/certs/ca-iryo.pem:ro
    # environment:
    # - DEBUG=1

  localMinio:
    image: minio/minio
    command:
    - server
    - /data
    environment:
<<<<<<< HEAD
    - MINIO_ACCESS_KEY=local
    - MINIO_SECRET_KEY=localminio
    ports:
    - 9000:9000
    volumes:
    - ./bin/tls/localMinio-key.pem:/root/.minio/certs/private.key
    - ./bin/tls/localMinio.pem:/root/.minio/certs/public.crt
    - ./.data/localMinio:/data

  cloudStorage:
    image: golang:1.9-alpine
    command:
    - /wwm/cloudStorage
    volumes:
    - ./.bin/:/wwm
    - ./bin/tls:/certs:ro
    - ./bin/tls/ca.pem:/etc/ssl/certs/ca-iryo.pem:ro
    # environment:
    # - DEBUG=1

  cloudMinio:
    image: minio/minio
    command:
    - server
    - /data
    environment:
    - MINIO_ACCESS_KEY=cloud
    - MINIO_SECRET_KEY=cloudminio
    volumes:
    - ./bin/tls/cloudMinio-key.pem:/root/.minio/certs/private.key
    - ./bin/tls/cloudMinio.pem:/root/.minio/certs/public.crt
    - ./.data/cloudMinio:/data
=======
      - DEBUG=1

  cloudAuth:
    image: alpine:latest
    command:
      - /wwm/cloudAuth
    ports:
      - 8511:80
    volumes:
      - ./.bin/:/wwm
    environment:
      - DEBUG=1
>>>>>>> Add swagger spec for auth
