defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    CertFile = "/certs/traefik.pem"
    KeyFile = "/certs/traefik-key.pem"

[web]
address = ":8080"

[file]

[backends]
  [backends.localauth]
    [backends.localauth.servers.server1]
    url = "https://localAuth"

  [backends.localstorage]
    [backends.localstorage.servers.server1]
    url = "https://localStorage"

  [backends.localMinio]
    [backends.localMinio.servers.server1]
    url = "https://localMinio:9000"

  [backends.cloudstorage]
    [backends.cloudstorage.servers.server1]
    url = "https://localStorage"

  [backends.cloudMinio]
    [backends.cloudMinio.servers.server1]
    url = "https://cloudMinio:9000"

  [backends.vaultui]
    [backends.vaultui.servers.server1]
    url = "http://vaultui:8000"

[frontends]
  [frontends.localauth]
  backend = "localauth"
    [frontends.localauth.routes.route1]
    rule = "Host:iryo.local;PathPrefix:/auth"

  [frontends.localstorage]
  backend = "localstorage"
    [frontends.localstorage.routes.route1]
    rule = "Host:iryo.local;PathPrefix:/storage"

  [frontends.localMinio]
  backend = "localMinio"
    [frontends.localMinio.routes.route1]
    rule = "Host:minio.iryo.local"

  [frontends.cloudstorage]
  backend = "cloudstorage"
    [frontends.cloudstorage.routes.route1]
    rule = "Host:iryo.cloud;PathPrefix:/storage"

  [frontends.cloudMinio]
  backend = "cloudMinio"
    [frontends.cloudMinio.routes.route1]
    rule = "Host:minio.iryo.cloud"

  [frontends.vaultui]
  backend = "vaultui"
    [frontends.vaultui.routes.route1]
    rule = "Host:vault.iryo.local"
