apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
    component: nodeport
  name: registry-nodeport
  namespace: registry
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30500
  selector:
    app: registry
    component: main
  sessionAffinity: None
